### ISSUE TITLE
Implement watchdog fix

### ISSUE THREAD

**Issue by danasf** [sudomesh/merakiflasher#1]
Hey sudo mesh,
Much appreciation for this tool! I flashed two Merakis with it yesterday, I'm using the GPIO pins, indirectly, to drive a pump and [lamp](https://vine.co/v/MH9zzZ3Z3nO).

To save a few minutes on flashing time I implemented Adrian's [watchdog fix](http://adrianchadd.blogspot.com/2014/03/meraki-sparky-boards-and-constant.html). 

I added 'keepalive' to self.cmds, and code to ensure pin 6 is set to output at the beginning of 'part1' :

```
        # Thx to Adrian for watchdog fix! http://adrianchadd.blogspot.com/2014/03/meraki-sparky-boards-and-constant.html   
        self.cmds = {
            'keepalive': [
                "mfill -b 0xb1000090 -l 4 -p 0x00000042",
                "mfill -b 0xb1000090 -l 4 -p 0x00000002"
                ],
            'part1': [
                "mfill -b 0xb1000098 -l 4 -p 0x00000043",
                "x -b 0xb1000098",
              ...
            }
```

I replaced the if-elif-else logic for progress tracking in `def flash(self)` with a single code block. I wasn't sure if you want to keep some form of progress checking, so opted for opening this issue rather than making a pull request.

```
            print "Flashing (~20 mins)"
            print "Flashing part 1 of 4 (~5 mins)"
            self.send_commands(self.cmds['part1'])
            print "Flashing part 2 of 4 (~5 mins)"
            self.send_commands(self.cmds['keepalive'])
            self.send_commands(self.cmds['part2'])
            print "Flashing part 3 of 4 (~5 mins)"
            self.send_commands(self.cmds['keepalive'])                
            self.send_commands(self.cmds['part3'])
            print "Flashing part 4 of 4 (~5 mins)"            
            self.send_commands(self.cmds['keepalive'])                
            self.send_commands(self.cmds['part4'])
            print "Flashing complete! Please reboot your router."
            exit(0)
```

There are far more elegant solutions but for the moment I'm using a shell script and cron job to keep openwrt up once it is installed. Works like a charm :)

```
#!/bin/sh
/usr/bin/gpioctl dirout 6
/usr/bin/gpioctl set 6
/usr/bin/gpioctl clear 6
exit 0
```

Thanks again!

**Comment by Juul** [comment]
Thanks Dana!

I'll integrate your changes :)

Your vine link didn't work. What's the project with the pump and lamp?

**Comment by danasf** [comment]
Excellent. That's weird about the Vine link --- I'm not sure why it's not working.

Watering and lighting plants! But in general I'm a fan of re-purposing routers for the internet-of-stuff tasks. And this router breaks out I/O pins very nicely. Maybe that's an avenue to add environmental sensors, automation, etc into the mesh? :)

I put up an [Instructable](http://www.instructables.com/id/Repurpose-an-old-wifi-router-for-the-internet-of-t/), primarily to encourage the general public and broader maker world to do more creative re-use of wifi routers ...

**Comment by jhpoelen** [comment]
Stale issue. Please re-open if needed.
